baseURL = 'https://inscribe.studio/'
languageCode = 'en-us'
title = 'Inscribe'
publishFuture = true

# SEO Configuration
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  subtitle = "Exploring the intersection of code, creativity, and the digital world"
  description = "A blog about programming, technology, creative writing and software development"
  author = "Sabique Islam"
  mode = "toggle"
  useCDN = false
  mainSections = ["posts"]
  favicon = "/favicon.svg"
  og_image = "/images/blog-cover.png"
  
  # SEO Settings
  enableRobotsTXT = true
  canonifyURLs = true
  
  # JSON-LD structured data
  jsonLD = true

  [[params.social]]
    name = "Portfolio"
    icon = "simple:wpexplorer"
    url = "https://sabique.vercel.app/"

  [[params.social]]
    name = "GitHub"
    icon = "simple:github"
    url = "https://github.com/Sabique-Islam"

  [[params.social]]
    name = "Instagram"
    icon = "simple:instagram"
    url = "https://www.instagram.com/bunsamosaa/"

  [[params.social]]
    name = "LinkedIn"
    icon = "simple:linkedin"
    url = "https://www.linkedin.com/in/sabique-islam/"

  [[params.social]]
    name = "Mail"
    icon = "simple:gmail"
    url = "mailto:sabiqueislam7@gmail.com"

  [[params.social]]
    name = "X (Twitter)"
    icon = "simple:x"
    url = "https://x.com/Sabique_"

  [[params.social]]
    name = "LeetCode"
    icon = "simple:leetcode"
    url = "https://leetcode.com/u/nopejs/"

  [[params.social]]
    name = "Spotify"
    icon = "simple:spotify"
    url = "https://open.spotify.com/user/31aa6sqh3runlghhznp4arpwwp54"

  [[params.social]]
    name = "Reddit"
    icon = "simple:reddit"
    url = "https://www.reddit.com/user/nope-js/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 4