baseURL = 'https://inscribe.studio/'
languageCode = 'en-us'
title = 'Inscribe'
publishFuture = true

# SEO Configuration
enableRobotsTXT = false
canonifyURLs = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  subtitle = "Exploring the intersection of code, creativity, and the digital world"
  description = "A blog about programming, technology, creative writing and software development"
  author = "Sabique"
  mode = "toggle"
  useCDN = false
  mainSections = ["posts"]
  favicon = "/images/icon.svg"
  og_image = "/images/blog-cover.png"
  
  # SEO Settings
  jsonLD = true
  
  # Social Media Metadata
  twitter_handle = "@nopeJS"
  twitter_creator = "@nopeJS"
  
  # Automatically generates social preview images for all pages
  screenshot_api_enabled = true

  # Portfolio & Dev
  [[params.social]]
    name = "Portfolio"
    icon = "simple:wpexplorer"
    url = "https://sabique.page/"

  [[params.social]]
    name = "Mail"
    icon = "simple:gmail"
    url = "mailto:mail@nopejs.me"

  # Social

  [[params.social]]
    name = "GitHub"
    icon = "simple:github"
    url = "https://github.com/Sabique-Islam"

  [[params.social]]
    name = "GitLab"
    icon = "simple:gitlab"
    url = "https://gitlab.com/nopejs"

  [[params.social]]
    name = "X"
    icon = "simple:x"
    url = "https://x.com/nopeJS"

  [[params.social]]
    name = "LinkedIn"
    icon = "simple:linkedin"
    url = "https://www.linkedin.com/in/sabique-islam/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 4